In [33]:
import pandas as pd
import numpy as np
import matplotlib as plt

import re

In [34]:
poetry_df = pd.read_csv("../data/poetry/kaggle_poem_dataset.csv").drop(['Unnamed: 0'],axis=1)
poetry_df

Author  \
0            Wendy Videlock   
1         Hailey Leithauser   
2             Jody Gladding   
3            Joseph Brodsky   
4              Ted Berrigan   
...                     ...   
15647         Hannah Gamble   
15648      Eleni Sikelianos   
15649  Susan Elizabeth Howe   
15650        Andrew Shields   
15651     Joseph O. Legaspi   

                                                   Title  \
0                                                      !   
1                                                      0   
2                                             1-800-FEAR   
3                                         1 January 1965   
4                                                3 Pages   
...                                                  ...   
15647              Your Invitation to a Modest Breakfast   
15648  Your Kingdom\n \n \n  \n   Launch Audio in a N...   
15649                     “Your Luck Is About To Change”   
15650                              Your Mileage May Vary   
15651                    Your Mother Wears a House Dress   

       Poetry Foundation ID                                            Content  
0                     55489  Dear Writers, I’m compiling the first in what ...  
1                     41729  Philosophic\nin its complex, ovoid emptiness,\...  
2                     57135  We'd  like  to  talk  with  you  about  fear t...  
3                     56736  The Wise Men will unlearn your name.\nAbove yo...  
4                     51624  For Jack Collom\n10 Things I do Every Day\n\np...  
...                     ...                                                ...  
15647                 56059  It’s too cold to smoke outside, but if you com...  
15648                145220  if you like let the body feel\nall its own evo...  
15649                 41696  (A fortune cookie)\nOminous inscrutable Chines...  
15650                 90177  1\nOur last night in the house was not our las...  
15651                 91304  If your house\nis a dress\nit’ll fit like\nLos...  

[15652 rows x 4 columns]

In [35]:
# this is not encoding punctuation correctly
news_df = pd.read_csv("../data/news/news_summary.csv", encoding="ISO-8859-1").dropna()
news_df["ctext"][1]

'From her special numbers to TV?appearances, Bollywood actor Malaika Arora Khan has managed to carve her own identity. The actor, who made her debut in the Hindi film industry with the blockbuster debut opposite Shah Rukh Khan in Chaiyya Chaiyya from Dil Se (1998), is still remembered for the song. However, for trolls, she is a woman first and what matters right now is that she divorced a ?rich man?.  On Wednesday, Malaika Arora shared a gorgeous picture of herself on Instagram and a follower decided to troll her for using her ?alumni? (read alimony) money to wear ?short clothes and going to gym or salon?. Little did he/she know that the Munni Badnam star would reply with the perfect comeback. Take a look at the interaction:     Super excited to be affiliated with Khanna Jewellers @khannajewellerskj as their brand ambassador. Crafted to perfection, their stunning statement jewellery is a must have for every jewellery lover. #khannajewellers...#maksquad?? #hair @hairbypriyanka #stylist 

In [36]:
# 10 authors with largest # of poems
poetry_df.groupby("Author")["Content"].count().sort_values()[-10:]

# Percy Bysshe Shelley always missing 2 letters
# poetry_df[poetry_df["Author"].apply(lambda s: "Shelley" in s)]

Author
Percy sshe Shelley       43
Yusef Komunyakaa         43
John Ashbery             46
William Butler Yeats     47
Emily Dickinson          57
William Wordsworth       59
Rae Armantrout           62
Alfred, Lord Tennyson    78
Anonymous                82
William Shakespeare      85
Name: Content, dtype: int64

In [37]:
from nltk.tokenize import word_tokenize
import nltk
#nltk.download('punkt')

In [38]:
def tokenize(poem):
    return word_tokenize(re.sub(r"\n", r" NN ", poem))

poetry_df["Tokenized"] = poetry_df["Content"].apply(lambda row: tokenize(row))

In [39]:
def count_token(tokenized, token_to_count):
    return sum([token==token_to_count for token in tokenized])

def num_lines(tokenized):
    print(tokenized)
    return (count_token(tokenized, "NN") + 1)

def num_words(tokenized):
    filtered = [token for token in tokenized if (token.isalnum() and token!="NN")]
    return len(filtered)

def num_punctuation(tokenized):
    filtered = [token for token in tokenized if (not token.isalnum() and token!="NN")]
    return len(filtered)

#(num_words(nltk_tokens), len(nltk_tokens), num_punctuation(nltk_tokens))

In [40]:
poetry_df["Num_lines"] = poetry_df["Tokenized"].apply(lambda row: num_lines(row), convert_dtype=False)
poetry_df["Num_words"] = poetry_df["Tokenized"].apply(lambda row: num_words(row), convert_dtype=False)
poetry_df["Num_punctuation"] = poetry_df["Tokenized"].apply(lambda row: num_punctuation(row), convert_dtype=False)

['Dear', 'Writers', ',', 'I', '’', 'm', 'compiling', 'the', 'first', 'in', 'what', 'I', 'hope', 'is', 'a', 'series', 'of', 'publications', 'I', '’', 'm', 'calling', 'artists', 'among', 'artists', '.', 'The', 'theme', 'for', 'issue', '1', 'is', '“', 'Faggot', 'Dinosaur.', '”', 'I', 'hope', 'to', 'hear', 'from', 'you', '!', 'Thank', 'you', 'and', 'best', 'wishes', '.']
['Philosophic', 'NN', 'in', 'its', 'complex', ',', 'ovoid', 'emptiness', ',', 'NN', 'a', 'skillful', 'pundit', 'coined', 'it', 'as', 'a', 'sort', 'NN', 'of', 'stopgap', 'doorstop', 'for', 'those', 'NN', 'quaint', 'equations', 'NN', 'NN', 'Romans', 'never', 'NN', 'dreamt', 'of', '.', 'In', 'form', 'completely', 'clever', 'NN', 'and', 'discrete—a', 'mirror', 'come', 'unsilvered', ',', 'NN', 'loose', 'watch', 'face', 'without', 'the', 'works', ',', 'NN', 'a', 'hollowed', 'globe', 'NN', 'NN', 'from', 'tip', 'to', 'toe', 'NN', 'unbroken', ',', 'it', 'evades', 'the', 'grappling', 'NN', 'hooks', 'of', 'mass', ',', 'tilts', 'the',

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



['Sidewalks', 'of', 'webs', 'and', 'weeds', 'NN', 'Run', 'parallel', 'to', 'empy', 'lots', 'where', 'foul', 'deeds', 'NN', 'By', 'handkerchief', 'heads', 'and', 'winos', 'were', 'played', ',', 'NN', 'To', 'that', 'old', 'house', 'where', 'we', 'stayed', '.', 'NN', 'Irma', 'Jean', ',', 'Cora', 'Jean', 'and', 'I', ',', 'three', 'debs', ',', 'NN', 'Against', 'the', 'cracks', 'of', 'weeds', 'and', 'webs', '.', 'NN', 'NN', 'Sitting', 'through', 'matinees', ',', 'dodging', 'chores', ',', 'NN', 'Chewing', 'gum', ';', 'claiming', 'boys', 'were', 'bores', '.', 'NN', 'But', 'secretly', 'grooming', 'hair', 'and', 'breasts', ';', 'NN', 'NN', 'Jennie', '’', 's', 'brood', ',', 'a', 'female', 'nest', '.', 'NN', 'Irma', ',', 'long-legged', ',', 'delicious', 'full', 'lips', ',', 'NN', 'Taught', 'Cora', 'and', 'me', 'to', 'wiggle', 'our', 'hips', '.', 'NN', 'George', 'Darlington', 'Love', ',', 'a', 'beau', ',', 'my', 'first', ';', 'NN', 'They', 'yelled', 'his', 'name', 'like', 'a', 'tribal', 'curse', 'N

In [41]:
poetry_df.groupby("Num_lines")["Title"].count().sort_values()

lines_14_df = poetry_df[poetry_df["Num_lines"] == 14]
lines_14_df

Author                                Title  \
40     Zachary Schomburg                  The Abandoned Hotel   
73     Siegfried Sassoon                           Absolution   
104         Donald Davie                       Across the Bay   
128       Rosemary Tonks         Addiction to an Old Mattress   
154            Nate Klug                               Advent   
...                  ...                                  ...   
15525     Hilaire Belloc                              The Yak   
15530       Don Thompson                            Yard Work   
15546      Roddy Lumsden                                Yeast   
15552         Fanny Howe                       Yellow Goblins   
15619  Trumbull Stickney  You Say, Columbus with his Argosies   

       Poetry Foundation ID  \
40                    56021   
73                    57212   
104                   54813   
128                   57642   
154                   53142   
...                     ...   
15525                 46686   
15530                 53605   
15546                 54540   
15552                 56293   
15619                 47442   

                                                 Content  \
40     Inside the woods is an abandoned hotel.\nTrees...   
73     The anguish of the earth absolves our eyes\nTi...   
104    A queer thing about those waters: there are no...   
128    No, this is not my life, thank God ...\n... wo...   
154    In the middle of December\nto start over\n\nto...   
...                                                  ...   
15525  As a friend to the children commend me the Yak...   
15530  My leaf blower lifted the blackbird—\nwings st...   
15546  A word you can’t quite say\nwithout itching, f...   
15552  Yellow goblins\nand a god I can swallow:\n\nEy...   
15619  You say, Columbus with his argosies\nWho rash ...   

                                               Tokenized Num_lines Num_words  \
40     [Inside, the, woods, is, an, abandoned, hotel,...        14        49   
73     [The, anguish, of, the, earth, absolves, our, ...        14       105   
104    [A, queer, thing, about, those, waters, :, the...        14        95   
128    [No, ,, this, is, not, my, life, ,, thank, God...        14        90   
154    [In, the, middle, of, December, NN, to, start,...        14        30   
...                                                  ...       ...       ...   
15525  [As, a, friend, to, the, children, commend, me...        14        94   
15530  [My, leaf, blower, lifted, the, blackbird—, NN...        14        70   
15546  [A, word, you, can, ’, t, quite, say, NN, with...        14       104   
15552  [Yellow, goblins, NN, and, a, god, I, can, swa...        14        30   
15619  [You, say, ,, Columbus, with, his, argosies, N...        14       104   

      Num_punctuation  
40                  8  
73                 17  
104                21  
128                26  
154                 0  
...               ...  
15525              15  
15530              14  
15546              24  
15552               5  
15619              12  

[899 rows x 8 columns]

In [42]:
#Create corpus, turn into dictionary


In [43]:
nltk

<module 'nltk' from '/Users/shreysahgal/opt/anaconda3/lib/python3.9/site-packages/nltk/__init__.py'>

In [44]:
%precision 2

'%.2f'

|  | News | Poetry |
| --- | --- | --- |
| Total samples | {{news_df["ctext"].nunique()}} | {{poetry_df["Content"].nunique()}}  |
| Unique authors | {{news_df["author"].nunique()}} | {{poetry_df["Author"].nunique()}} |
| Mean words per sample (SD) | {{news_df["author"].nunique()}} | {{poetry_df["Num_words"].mean()}} ({{poetry_df["Num_words"].std()}})|
| Mean new lines per sample (SD) | {{news_df["author"].nunique()}} | {{poetry_df["Num_lines"].mean()}} ({{poetry_df["Num_lines"].std()}}) |
| Mean punctuation marks per sample (SD) | {{news_df["author"].nunique()}} | {{poetry_df["Num_punctuation"].mean()}} ({{poetry_df["Num_punctuation"].std()}}) |

In [45]:
poetry_df

Author  \
0            Wendy Videlock   
1         Hailey Leithauser   
2             Jody Gladding   
3            Joseph Brodsky   
4              Ted Berrigan   
...                     ...   
15647         Hannah Gamble   
15648      Eleni Sikelianos   
15649  Susan Elizabeth Howe   
15650        Andrew Shields   
15651     Joseph O. Legaspi   

                                                   Title  \
0                                                      !   
1                                                      0   
2                                             1-800-FEAR   
3                                         1 January 1965   
4                                                3 Pages   
...                                                  ...   
15647              Your Invitation to a Modest Breakfast   
15648  Your Kingdom\n \n \n  \n   Launch Audio in a N...   
15649                     “Your Luck Is About To Change”   
15650                              Your Mileage May Vary   
15651                    Your Mother Wears a House Dress   

       Poetry Foundation ID  \
0                     55489   
1                     41729   
2                     57135   
3                     56736   
4                     51624   
...                     ...   
15647                 56059   
15648                145220   
15649                 41696   
15650                 90177   
15651                 91304   

                                                 Content  \
0      Dear Writers, I’m compiling the first in what ...   
1      Philosophic\nin its complex, ovoid emptiness,\...   
2      We'd  like  to  talk  with  you  about  fear t...   
3      The Wise Men will unlearn your name.\nAbove yo...   
4      For Jack Collom\n10 Things I do Every Day\n\np...   
...                                                  ...   
15647  It’s too cold to smoke outside, but if you com...   
15648  if you like let the body feel\nall its own evo...   
15649  (A fortune cookie)\nOminous inscrutable Chines...   
15650  1\nOur last night in the house was not our las...   
15651  If your house\nis a dress\nit’ll fit like\nLos...   

                                               Tokenized Num_lines Num_words  \
0      [Dear, Writers, ,, I, ’, m, compiling, the, fi...         1        40   
1      [Philosophic, NN, in, its, complex, ,, ovoid, ...        17        64   
2      [We, 'd, like, to, talk, with, you, about, fea...        11       113   
3      [The, Wise, Men, will, unlearn, your, name, .,...        26       147   
4      [For, Jack, Collom, NN, 10, Things, I, do, Eve...        39        79   
...                                                  ...       ...       ...   
15647  [It, ’, s, too, cold, to, smoke, outside, ,, b...        35       229   
15648  [if, you, like, let, the, body, feel, NN, all,...        41       198   
15649  [(, A, fortune, cookie, ), NN, Ominous, inscru...        25       146   
15650  [1, NN, Our, last, night, in, the, house, was,...         5        30   
15651  [If, your, house, NN, is, a, dress, NN, it, ’,...        22        57   

      Num_punctuation  
0                   9  
1                  12  
2                   5  
3                  26  
4                   6  
...               ...  
15647              43  
15648              18  
15649              37  
15650               4  
15651              12  

[15652 rows x 8 columns]

In [46]:
# Train supervised learning model
# Pre-processing: Tokenized poems, select poems with a static N number of lines, or use all poems and truncate
# Input: [array of strings], padded for word count
# Output: [array of strings with newlines inserted]
# Loss: sum of distance between words per line
set(poetry_df['Tokenized'].explode())

#[item for sublist in poetry_df['Tokenized'] for item in poetry_df['Tokenized']]

{'popular',
 'cilantro',
 'ærende',
 'permission—the',
 'Lycke',
 'foot-way',
 'stardust',
 'gaiter',
 'þeraboute',
 'Debased',
 'Facing',
 'scars-football',
 'inconclusion',
 'angel',
 'voles',
 'fluvial',
 'Subject',
 'adod',
 'broncho',
 'repositories',
 'cottonwood',
 'pearldiving',
 'twig-littered',
 'quarterbacks',
 'yester-night',
 'Llywarch—the',
 'unbowed',
 'sleke',
 'Ninavah',
 'ongite',
 'unrepenting',
 'unfelled',
 'Birthright',
 'sorgcearig',
 'Yep',
 'eotenas',
 'Rudiment',
 'you—there',
 'inexhaustibly',
 'placenta',
 'Cerastes',
 'Pierre',
 'Hatz',
 'fyrdwyrðe',
 'wowez',
 'Masses',
 'urine-soaked',
 'Welcoming',
 'reconciled',
 'wellness',
 'Quaint',
 'Poca',
 'ocean-waves',
 'Waisa',
 'Galatian',
 'feverish',
 'Daulis',
 'close-walking',
 'accomplishing',
 'Regulations',
 'venged',
 'loped',
 'face—false',
 'unsilvered',
 'passports',
 'Keaton-faced',
 'smiles.My',
 'smooth—nor',
 'addeth',
 'sullenness',
 'flutterings—I',
 'GATEWAY',
 'tun',
 'mantis',
 'Generally',

In [47]:
# from nltk.corpus import stopwords
# from nltk.tokenize import word_tokenize, sent_tokenize
#nltk.download('stopwords')

# from gensim.models import Word2Vec
# >>> from nltk.corpus import brown, movie_reviews, treebank
# >>> b = Word2Vec(brown.sents())
# >>> mr = Word2Vec(movie_reviews.sents())
# >>> t = Word2Vec(treebank.sents())

# stopwords = set(stopwords.words("english"))
# words = poetry_df['Tokenized'][0]

# nltk.Word2Vec(words)

def make_token_dict(full_corpus):
    word_dict = {val : idx + 1 for idx, val in enumerate(set(full_corpus))}
    return word_dict

def apply_token_dict(token_dict, token_list):
    return [token_dict[token]  if token!="NN" else "NN" for token in token_list]

def create_model_input_vec(dict_list, input_size):
    # List without newlines
    input_vec = np.zeros(input_size)
    
#     print(len(dict_list))
    
    i = 0
    for token in dict_list:
        if token != "NN":
            input_vec[i] = token
            i += 1
#     return np.array([token for token in dict_list if token!="NN"])
    return input_vec

def create_model_output_vec(dict_list, num_lines):
    # Output is vector 
    # [5, 4, 1, 10, ... , 16], len = 14
    output_vec = np.zeros(num_lines)
    i=0
    for token in dict_list:
        if token=="NN":
            i+=1
        else:
            output_vec[i]+=1
    assert (len(dict_list)-num_lines+1)==sum(output_vec)
    
    return output_vec

In [100]:
input_size = 349 # from data

token_dict = make_token_dict(poetry_df['Tokenized'].explode())
poetry_df["Dict_tokens"] = poetry_df["Tokenized"].apply(lambda s: apply_token_dict(token_dict, s))
poetry_df["Input_vec"] = poetry_df[poetry_df["Num_lines"] == 14]["Dict_tokens"].apply(lambda s: create_model_input_vec(s, input_size))
poetry_df["Output_vec"] = poetry_df.apply(lambda s: create_model_output_vec(s["Dict_tokens"], s["Num_lines"]), axis=1)


In [49]:
X = np.stack(poetry_df[poetry_df["Num_lines"] == 14]["Input_vec"].values)
Y = np.stack(poetry_df[poetry_df["Num_lines"] == 14]["Output_vec"].values)

In [50]:
import tensorflow as tf

X = tf.convert_to_tensor(X)
Y = tf.convert_to_tensor(Y)

In [51]:
X_train = X[:800]
Y_train = Y[:800]

X_test = X[800:]
Y_test = Y[800:]

X_train[0]

<tf.Tensor: shape=(349,), dtype=float64, numpy=
array([ 67105., 118739.,  36400., 138150., 125402.,  29071.,   9702.,
        57938.,  25655.,  68027.,  73526., 118739., 159445.,  22398.,
       138903.,  94128., 118739., 164120.,  57938., 153928., 164283.,
       165307.,  94128., 118739.,   2630.,  57938., 116178.,  62446.,
        97109., 101641.,  49750.,  57938.,  75508., 117200., 118739.,
        86829.,  94128., 158989., 164120.,  57938.,  75508.,  88015.,
        38230., 124983.,  73526., 120341., 153788.,  72950.,  57938.,
       103866.,  99052., 119431.,   6800.,  36212.,  22278.,  32975.,
        57938.,      0.,      0.,      0.,      0.,      0.,      0.,
            0.,      0.,      0.,      0.,      0.,      0.,      0.,
            0.,      0.,      0.,      0.,      0.,      0.,      0.,
            0.,      0.,      0.,      0.,      0.,      0.,      0.,
            0.,      0.,      0.,      0.,      0.,      0.,      0.,
            0.,      0.,      0.,      0.,

In [60]:
# define model
# input size -> 349
# layer 1 -> 150
# layer 2 -> 75
# layer 3 -> 30
# output size -> 14

# first neural network with keras tutorial
from keras.models import Sequential
from keras.layers import Dense


model = Sequential()
model.add(Dense(150, input_dim=349, activation='relu'))
model.add(Dense(75, activation='tanh'))
model.add(Dense(30, activation='relu'))
model.add(Dense(14, activation='relu'))


In [122]:
import tensorflow as tf

# loss function
def poem_loss(y_true, y_pred):    
    item_loss = tf.matmul((y_true - y_pred), tf.transpose((y_true - y_pred)))
    word_sum_loss = 1000*(tf.math.reduce_sum(y_true) - tf.math.reduce_sum(y_pred))**2
    
    return item_loss + word_sum_loss

# hyperparams
epochs = 100
batch_size = 20

X_train = tf.convert_to_tensor(X_train)
Y_train = tf.convert_to_tensor(Y_train)

model.compile(loss="msle", optimizer='adam', metrics=['accuracy'])
model.fit(X_train, Y_train, epochs=epochs, batch_size=batch_size, validation_data=(X_test, Y_test))

_, accuracy = model.evaluate(X_test, Y_test)
print('Accuracy: %.2f' % (accuracy*100))

Epoch 1/100
40/40 [==============================] - 1s 10ms/step - loss: 0.2478 - accuracy: 0.0988 - val_loss: 0.2226 - val_accuracy: 0.0707
Epoch 2/100
40/40 [==============================] - 0s 4ms/step - loss: 0.2471 - accuracy: 0.1037 - val_loss: 0.2217 - val_accuracy: 0.0606
Epoch 3/100
40/40 [==============================] - 0s 4ms/step - loss: 0.2469 - accuracy: 0.0950 - val_loss: 0.2237 - val_accuracy: 0.0707
Epoch 4/100
40/40 [==============================] - 0s 5ms/step - loss: 0.2469 - accuracy: 0.1013 - val_loss: 0.2271 - val_accuracy: 0.0606
Epoch 5/100
40/40 [==============================] - 0s 4ms/step - loss: 0.2469 - accuracy: 0.0913 - val_loss: 0.2286 - val_accuracy: 0.0808
Epoch 6/100
40/40 [==============================] - 0s 4ms/step - loss: 0.2489 - accuracy: 0.0900 - val_loss: 0.2267 - val_accuracy: 0.0505
Epoch 7/100
40/40 [==============================] - 0s 5ms/step - loss: 0.2471 - accuracy: 0.1063 - val_loss: 0.2221 - val_accuracy: 0.0606
Epoch 8/100


Epoch 59/100
40/40 [==============================] - 0s 5ms/step - loss: 0.2455 - accuracy: 0.0913 - val_loss: 0.2281 - val_accuracy: 0.0808
Epoch 60/100
40/40 [==============================] - 0s 5ms/step - loss: 0.2458 - accuracy: 0.0925 - val_loss: 0.2252 - val_accuracy: 0.0707
Epoch 61/100
40/40 [==============================] - 0s 5ms/step - loss: 0.2458 - accuracy: 0.0988 - val_loss: 0.2262 - val_accuracy: 0.0707
Epoch 62/100
40/40 [==============================] - 0s 4ms/step - loss: 0.2447 - accuracy: 0.0975 - val_loss: 0.2225 - val_accuracy: 0.0707
Epoch 63/100
40/40 [==============================] - 0s 5ms/step - loss: 0.2453 - accuracy: 0.0975 - val_loss: 0.2209 - val_accuracy: 0.0909
Epoch 64/100
40/40 [==============================] - 0s 5ms/step - loss: 0.2459 - accuracy: 0.1063 - val_loss: 0.2220 - val_accuracy: 0.0505
Epoch 65/100
40/40 [==============================] - 0s 5ms/step - loss: 0.2454 - accuracy: 0.0938 - val_loss: 0.2228 - val_accuracy: 0.0707
Epoch 

In [123]:
i = 200

poem = poetry_df[poetry_df["Num_lines"] == 14]["Content"].iloc[i]
x = poetry_df[poetry_df["Num_lines"] == 14]["Input_vec"].iloc[i].reshape(1, 349)
y = poetry_df[poetry_df["Num_lines"] == 14]["Output_vec"].iloc[i]
poem.split('\n')

['Last night I heard your voice, mother,',
 'The words you sang to me',
 'When I, a little barefoot boy,',
 'Knelt down against your knee.',
 '',
 'And tears gushed from my heart, mother,',
 'And passed beyond its wall,',
 'But though the fountain reached my throat',
 'The drops refused to fall.',
 '',
 "'Tis ten years since you died, mother,",
 'Just ten dark years of pain,',
 'And oh, I only wish that I',
 'Could weep just once again.']

In [124]:
x = tf.convert_to_tensor(x)

In [125]:
model.predict(x)

array([[7.88, 8.1 , 6.97, 7.72, 3.05, 7.55, 7.88, 7.31, 6.65, 3.19, 7.92,
        7.39, 8.21, 8.26]], dtype=float32)

In [126]:
y

array([ 9.,  6.,  8.,  6.,  0.,  9.,  6.,  7.,  6.,  0., 10.,  7.,  8.,
        6.])

In [80]:
newlin_mean_y = np.array([[1 if i==0 else 0 for i in y] for y in np.array(Y)])
newlin_mean_y.mean(axis=0)

array([0.  , 0.02, 0.05, 0.02, 0.23, 0.05, 0.02, 0.02, 0.06, 0.24, 0.01,
       0.06, 0.02, 0.  ])

In [59]:
Y

<tf.Tensor: shape=(899, 14), dtype=float64, numpy=
array([[ 8.,  5.,  6., ...,  5.,  0.,  8.],
       [ 8., 10., 12., ..., 11.,  9., 11.],
       [10.,  7., 10., ...,  8.,  8., 12.],
       ...,
       [ 8., 10.,  7., ..., 11., 12., 11.],
       [ 2.,  7.,  0., ...,  0.,  4.,  2.],
       [ 7.,  8.,  6., ...,  9., 12.,  8.]])>

In [83]:
def poemize_prediction(content, pred):
    content = content.split(' ')
    s = 0
    for i in pred[0]:
        s += i+1
        content.insert(int(round(s)), '\n')
    content = ' '.join(content)
    return '\n'.join([i.strip() for i in content.split('\n')])

In [127]:
news = """So, for now, many governments are more urgently focused on reducing near term energy shocks, 
aiming to boost global oil production to replace the millions of barrels per day that Russia has historically 
exported but which is now being shunned by Western nations. The two goals aren’t necessarily at odds, officials 
in the United States and Europe say. Yet some fear that countries could become so consumed by the immediate 
energy crisis that they neglect longer term policies to cut reliance on fossil fuels — a myopia 
that could set the world up for more oil and gas shocks in the future as well as a dangerously overheated planet.""".replace('\n', '')

In [128]:
tokens = tokenize(news)
tokens = apply_token_dict(token_dict, tokens)
input_vec = create_model_input_vec(tokens, input_size)

In [129]:
pred = model.predict(np.array([input_vec]))

In [130]:
print(poemize_prediction(news, pred))

So, for now, many governments are more urgently focused on reducing
near term energy shocks, aiming to boost global oil production
to replace the millions of barrels per day that
Russia has historically exported but which is now being shunned
by Western nations. The two goals aren’t
necessarily at odds, officials in the United States and Europe
say. Yet some fear that countries could become so consumed
by the immediate energy crisis that they neglect longer
term policies to cut reliance on fossil fuels — a
myopia that could set the world up
for more oil and gas shocks in the future as
well as a dangerously overheated planet.





**Input:** <br>
So, for now, many governments are more urgently focused on reducing near term energy shocks, 
aiming to boost global oil production to replace the millions of barrels per day that Russia has historically 
exported but which is now being shunned by Western nations. The two goals aren’t necessarily at odds, officials 
in the United States and Europe say. Yet some fear that countries could become so consumed by the immediate 
energy crisis that they neglect longer term policies to cut reliance on fossil fuels — a myopia 
that could set the world up for more oil and gas shocks in the future as well as a dangerously overheated planet.

**Model 1 output:** <br>
So, for now, many governments are more urgently focused on reducing<br>
near term energy shocks, aiming to boost global oil production<br>
to replace the millions of barrels per day that<br>
Russia has historically exported but which is now being shunned<br>
by Western nations. The two goals aren’t<br>
necessarily at odds, officials in the United States and Europe<br>
say. Yet some fear that countries could become so consumed<br>
by the immediate energy crisis that they neglect longer<br>
term policies to cut reliance on fossil fuels — a<br>
myopia that could set the world up<br>
for more oil and gas shocks in the future as<br>
well as a dangerously overheated planet.<br>